 
2021-12-05 19:36:35,711 [INFO] server_connection: Установлено соединение ('127.0.0.1', 54096) с сервером ('127.0.0.1', 9090)
2021-12-05 19:36:40,119 [INFO] server_connection: Установлено соединение ('127.0.0.1', 54098) с сервером ('127.0.0.1', 9090)
2021-12-05 19:36:45,722 [INFO] success: Клиент ('127.0.0.1', 54098) прошел авторизацию
2021-12-05 19:36:48,199 [INFO] server_sync: Отправка данных от ('127.0.0.1', 54098) на сервер: hay
2021-12-05 19:36:50,272 [INFO] receive_data: ('127.0.0.1', 54098) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| File      | test_copy.txt |
| Directory | 444           |
| File      | 1.txt         |
2021-12-05 19:37:06,096 [INFO] receive_data: ('127.0.0.1', 54098) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| File      | test_copy.txt |
| Directory | 444           |
| File      | 1.txt         |
2021-12-05 19:37:20,849 [INFO] receive_data: ('127.0.0.1', 54098) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| File      | test_copy.txt |
| Directory | 444           |
| File      | 1.txt         |
2021-12-05 19:41:17,578 [INFO] receive_data: ('127.0.0.1', 54098) получил данные от сервера: Файл 23.txt успешно перенесён на сервер
2021-12-05 19:41:21,339 [INFO] receive_data: ('127.0.0.1', 54098) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-05 19:41:23,962 [INFO] server_sync: Отправка данных от ('127.0.0.1', 54098) на сервер: cat
2021-12-05 19:49:27,023 [INFO] server_connection: Установлено соединение ('127.0.0.1', 54184) с сервером ('127.0.0.1', 9090)
2021-12-05 19:49:29,887 [INFO] server_connection: Установлено соединение ('127.0.0.1', 54186) с сервером ('127.0.0.1', 9090)
2021-12-05 19:49:39,858 [INFO] success: Клиент ('127.0.0.1', 54186) прошел авторизацию
2021-12-05 19:49:43,305 [INFO] receive_data: ('127.0.0.1', 54186) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-05 19:49:48,104 [INFO] receive_data: ('127.0.0.1', 54186) получил данные от сервера: dsadsadsad
2021-12-05 20:10:37,429 [INFO] server_connection: Установлено соединение ('127.0.0.1', 49860) с сервером ('127.0.0.1', 9091)
2021-12-05 20:10:42,151 [INFO] success: Клиент ('127.0.0.1', 49860) прошел авторизацию
2021-12-05 20:10:44,694 [INFO] receive_data: ('127.0.0.1', 49860) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-05 20:10:50,366 [INFO] receive_data: ('127.0.0.1', 49860) получил данные от сервера: Успешный переход в директорию 444
Текущий путь: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage/444
2021-12-05 20:10:56,438 [INFO] receive_data: ('127.0.0.1', 49860) получил данные от сервера: 
2021-12-05 20:11:03,990 [INFO] receive_data: ('127.0.0.1', 49860) получил данные от сервера: Успешный переход в директорию server_storage
Текущий путь: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage
2021-12-05 20:11:09,829 [INFO] receive_data: ('127.0.0.1', 49860) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-05 20:11:54,286 [INFO] server_connection: Установлено соединение ('127.0.0.1', 54282) с сервером ('127.0.0.1', 9090)
2021-12-05 20:11:56,302 [INFO] server_connection: Установлено соединение ('127.0.0.1', 54284) с сервером ('127.0.0.1', 9090)
2021-12-05 20:12:00,536 [INFO] success: Клиент ('127.0.0.1', 54284) прошел авторизацию
2021-12-05 20:12:12,447 [INFO] receive_data: ('127.0.0.1', 54284) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-05 20:12:14,718 [INFO] receive_data: ('127.0.0.1', 54284) получил данные от сервера: Ошибка доступа!
Невозможно переместиться выше заданной корневой директории (server_storage)
2021-12-05 20:12:22,078 [INFO] server_sync: Отправка данных от ('127.0.0.1', 54284) на сервер: cd 444
2021-12-06 20:02:12,075 [INFO] server_connection: Установлено соединение ('127.0.0.1', 45712) с сервером ('127.0.0.1', 9091)
2021-12-06 20:02:31,034 [INFO] server_connection: Установлено соединение ('127.0.0.1', 45716) с сервером ('127.0.0.1', 9091)
2021-12-06 20:02:39,501 [INFO] success: Клиент ('127.0.0.1', 45716) прошел авторизацию
2021-12-06 20:02:48,209 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-06 20:02:56,276 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-06 20:02:57,371 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage
2021-12-06 20:03:13,971 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: asdsaddsad hello world! 

2021-12-06 20:03:23,375 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: Директория "555" успешно создана
2021-12-06 20:03:24,850 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: |:----------|:--------------|
| Directory | 555           |
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-06 20:03:30,134 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: Успешный переход в директорию 555
Текущий путь: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage/555
2021-12-06 20:03:33,088 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: Успешный переход в директорию server_storage
Текущий путь: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage
2021-12-06 20:03:36,733 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: Ошибка доступа!
Невозможно переместиться выше заданной корневой директории (server_storage)
2021-12-06 20:03:51,195 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: |:----------|:--------------|
| Directory | 555           |
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-06 20:06:05,589 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: |:----------|:--------------|
| Directory | 555           |
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-06 20:06:08,079 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage
2021-12-06 20:06:10,070 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage
2021-12-06 20:06:18,001 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage
2021-12-06 20:06:19,157 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: |:----------|:--------------|
| Directory | 555           |
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-06 20:06:24,910 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: Успешный переход в директорию 444
Текущий путь: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage/444
2021-12-06 20:06:25,682 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: 
2021-12-06 20:06:29,064 [INFO] server_sync: Отправка данных от ('127.0.0.1', 45716) на сервер: touch
2021-12-06 20:06:30,971 [INFO] server_sync: Отправка данных от ('127.0.0.1', 45716) на сервер: touch
2021-12-06 20:06:38,955 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: Директория "675" успешно создана
2021-12-06 20:06:40,715 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: |:----------|----:|
| Directory | 675 |
2021-12-06 20:06:42,748 [INFO] server_sync: Отправка данных от ('127.0.0.1', 45716) на сервер: cd 675
2021-12-06 20:06:45,544 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: |:----------|----:|
| Directory | 675 |
2021-12-06 20:06:47,943 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: |:----------|----:|
| Directory | 675 |
2021-12-06 20:06:51,634 [INFO] server_sync: Отправка данных от ('127.0.0.1', 45716) на сервер: cd 675
2021-12-06 20:06:55,321 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: Успешный переход в директорию 675
Текущий путь: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage/444/675
2021-12-06 20:06:57,406 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: 
2021-12-06 20:06:59,395 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: Успешный переход в директорию 444
Текущий путь: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage/444
2021-12-06 20:07:01,259 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: Успешный переход в директорию server_storage
Текущий путь: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage
2021-12-06 20:07:03,121 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: Ошибка доступа!
Невозможно переместиться выше заданной корневой директории (server_storage)
2021-12-06 20:07:14,704 [INFO] receive_data: ('127.0.0.1', 45716) получил данные от сервера: |:----------|:--------------|
| Directory | 555           |
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-22 19:41:15,210 [INFO] server_connection: Установлено соединение ('127.0.0.1', 33968) с сервером ('127.0.0.1', 9090)
2021-12-22 19:41:29,980 [INFO] server_connection: Установлено соединение ('127.0.0.1', 33970) с сервером ('127.0.0.1', 9090)
2021-12-22 19:41:48,853 [INFO] server_connection: Установлено соединение ('127.0.0.1', 33972) с сервером ('127.0.0.1', 9090)
2021-12-22 19:42:03,952 [INFO] success: Клиент ('127.0.0.1', 33972) прошел авторизацию
2021-12-22 19:42:14,627 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: |:----------|:--------------|
| Directory | 555           |
| File      | 2.txt         |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-22 19:43:30,422 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage
2021-12-22 19:44:42,094 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: Директория "new_dir" успешно создана
2021-12-22 19:44:44,386 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: |:----------|:--------------|
| Directory | 555           |
| File      | 2.txt         |
| Directory | new_dir       |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
| File      | 1.txt         |
2021-12-22 19:46:36,959 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: Директория "555" успешно удалена
2021-12-22 19:47:10,482 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: Файл "1.txt" успешно удалён
2021-12-22 19:47:19,463 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| Directory | new_dir       |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
2021-12-22 19:48:29,893 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: asdsaddsad hello world! 

2021-12-22 19:49:25,706 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: Ошибка: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage/h - No such file or directory
2021-12-22 19:51:21,826 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: Ошибка: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage/r - No such file or directory
2021-12-22 19:51:37,901 [INFO] receive_data: ('127.0.0.1', 33972) получил данные от сервера: Ошибка: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage/3 - Device or resource busy
2021-12-22 19:53:45,129 [INFO] server_connection: Установлено соединение ('127.0.0.1', 56832) с сервером ('127.0.0.1', 9091)
2021-12-22 19:53:57,204 [INFO] server_connection: Установлено соединение ('127.0.0.1', 56834) с сервером ('127.0.0.1', 9091)
2021-12-22 19:54:09,425 [INFO] server_connection: Установлено соединение ('127.0.0.1', 56836) с сервером ('127.0.0.1', 9091)
2021-12-22 19:54:22,562 [INFO] server_connection: Установлено соединение ('127.0.0.1', 56842) с сервером ('127.0.0.1', 9091)
2021-12-22 19:54:34,716 [INFO] server_connection: Установлено соединение ('127.0.0.1', 34000) с сервером ('127.0.0.1', 9090)
2021-12-22 19:54:48,745 [INFO] server_connection: Установлено соединение ('127.0.0.1', 34002) с сервером ('127.0.0.1', 9090)
2021-12-22 19:54:55,510 [INFO] success: Клиент ('127.0.0.1', 34002) прошел авторизацию
2021-12-22 19:55:03,290 [INFO] receive_data: ('127.0.0.1', 34002) получил данные от сервера: |:----------|:--------------|
| File      | 2.txt         |
| Directory | new_dir       |
| File      | test_copy.txt |
| File      | 23.txt        |
| Directory | 444           |
2021-12-22 19:55:17,171 [INFO] receive_data: ('127.0.0.1', 34002) получил данные от сервера: Файл "2.txt" успешно переименован в "hello_world.txt"
2021-12-22 19:55:20,394 [INFO] receive_data: ('127.0.0.1', 34002) получил данные от сервера: |:----------|:----------------|
| Directory | new_dir         |
| File      | test_copy.txt   |
| File      | 23.txt          |
| Directory | 444             |
| File      | hello_world.txt |
2021-12-22 19:56:17,150 [INFO] receive_data: ('127.0.0.1', 34002) получил данные от сервера: asdsaddsad hello world! 

2021-12-22 19:57:11,498 [INFO] receive_data: ('127.0.0.1', 34002) получил данные от сервера: |:----------|:----------------|
| Directory | new_dir         |
| File      | test_copy.txt   |
| File      | 23.txt          |
| Directory | 444             |
| File      | hello_world.txt |
2021-12-22 19:57:19,507 [INFO] receive_data: ('127.0.0.1', 34002) получил данные от сервера: Успешный переход в директорию 444
Текущий путь: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage/444
2021-12-22 19:57:35,821 [INFO] receive_data: ('127.0.0.1', 34002) получил данные от сервера: Успешный переход в директорию server_storage
Текущий путь: /home/noble6/DEV/Study_Practice/Python/FTPServer/server_storage
2021-12-22 19:57:38,004 [INFO] receive_data: ('127.0.0.1', 34002) получил данные от сервера: Ошибка доступа!
Невозможно переместиться выше заданной корневой директории (server_storage)
2021-12-22 19:58:22,854 [INFO] receive_data: ('127.0.0.1', 34002) получил данные от сервера: |:----------|:----------------|
| Directory | new_dir         |
| File      | test_copy.txt   |
| File      | 23.txt          |
| Directory | 444             |
| File      | hello_world.txt |
2021-12-22 19:58:28,222 [INFO] receive_data: ('127.0.0.1', 34002) получил данные от сервера: |:----------|:----------------|
| Directory | new_dir         |
| File      | test_copy.txt   |
| File      | 23.txt          |
| Directory | 444             |
| File      | hello_world.txt |
2021-12-22 20:00:44,516 [INFO] server_connection: Установлено соединение ('127.0.0.1', 56882) с сервером ('127.0.0.1', 9091)
2021-12-22 20:00:56,834 [INFO] server_connection: Установлено соединение ('127.0.0.1', 56884) с сервером ('127.0.0.1', 9091)
2021-12-22 20:01:01,939 [INFO] success: Клиент ('127.0.0.1', 56884) прошел авторизацию
2021-12-22 20:01:03,919 [INFO] receive_data: ('127.0.0.1', 56884) получил данные от сервера: |:----------|:----------------|
| Directory | new_dir         |
| File      | test_copy.txt   |
| File      | 23.txt          |
| Directory | 444             |
| File      | hello_world.txt |
2021-12-22 20:06:13,785 [INFO] server_connection: Установлено соединение ('127.0.0.1', 34046) с сервером ('127.0.0.1', 9090)
2021-12-22 20:06:19,084 [INFO] success: Клиент ('127.0.0.1', 34046) прошел авторизацию
2021-12-22 20:06:47,958 [ERROR] client_server_transfer: Произошла ошибка при копировании файла с клиента на сервер
2021-12-22 20:06:47,959 [INFO] receive_data: ('127.0.0.1', 34046) получил данные от сервера: argument should be a bytes-like object or ASCII string, not 'NoneType'
2021-12-22 20:06:55,169 [INFO] receive_data: ('127.0.0.1', 34046) получил данные от сервера: |:----------|:----------------|
| Directory | new_dir         |
| File      | test_copy.txt   |
| File      | 23.txt          |
| Directory | 444             |
| File      | hello_world.txt |
2021-12-22 20:07:10,614 [INFO] receive_data: ('127.0.0.1', 34046) получил данные от сервера: Файл from_client.txt успешно перенесён на сервер
2021-12-22 20:07:13,087 [INFO] receive_data: ('127.0.0.1', 34046) получил данные от сервера: |:----------|:----------------|
| File      | from_client.txt |
| Directory | new_dir         |
| File      | test_copy.txt   |
| File      | 23.txt          |
| Directory | 444             |
| File      | hello_world.txt |
2021-12-22 20:07:37,329 [INFO] receive_data: ('127.0.0.1', 34046) получил данные от сервера: 12345 server

2021-12-22 20:10:29,440 [INFO] receive_data: ('127.0.0.1', 34046) получил данные от сервера: tester выключил сервер
